### PR TITLE
Update Module_4_Lab.md

### PR DESCRIPTION
**Pull request by cjpluta**
Changed 'sh' to 'Bash' to match Cloud Shell UI

Broke out multiple commands into separate code segments for ALH integration.

# Module: 00
## Lab/Demo: 00

Fixes # .

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by polichtm** [comment]
Hi Charles,
would you mind clarifying what specifically is the issue you're running into?
rgds
Marcin

**Comment by cjpluta** [comment]
Hey Marcin,

We use Learn on Demand Systems as our lab hosting provider at Microsoft for
any customer class.
A limitation of the LODS system is that students can't copy/paste from
their local machines to the lab environment. LODS workaround is to use
'TypeText' buttons in their instructions.
[image: image.png]
The biggest change I made in the PR for the M4 lab is that if there is a
variable that needs to be set, it can't be in the same code block as a
command that runs after it. If the student hits the 'T', it types the full
code block. And so if the first line is
$location = '<Azure Region>'

They literally set the variable in Cloud Shell to the string, and it
automatically enters the carriage return, and they don't get a chance to
edit it.

We get *a lot* of people in our classes that have never used the Azure
portal before, have no idea what they are doing in Cloud Shell, etc. So
trying to make it as simple as possible. Thats also why I changed 'sh' to
'Bash' in the label, since that is what Cloud Shell displays.

Hope that helps provide context.
Thx,
Charles

**Comment by polichtm** [comment]
Hi Charles,
It appears that you meant to attach a screenshot - can you provide it?
Could you clarify why students are seeing the markdown code?
rgds
Marcin

**Comment by cjpluta** [comment]
Hm, guess the screenshot doesn't work over email. Should be below.

Its not that the students see the Markdown, its a feature of Learn on Demand to auto-type code segments. Let me know if you want to hop on a call and I can show you too.
Thx

image

**Comment by polichtm** [comment]
Hi Charles,
appreciate the clarification - all good...
rgds
Marcin

**Pull request merged**
